# Generated by Django 5.0.4 on 2024-06-20 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksiz', models.IntegerField(blank=True, default=680, null=True, verbose_name="Aksiz solig'")),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': " Aksiz so'lig'",
                'verbose_name_plural': " Aksiz so'lig'",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Buyprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyprice', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gazdi sotilgan narxi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': ' Gazdi olingan narxi',
                'verbose_name_plural': 'Gazdi olingan narxi',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Filial nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Xisob raqamlar nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Losegas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('losegas', models.FloatField(blank=True, default=1.4, null=True, verbose_name="1.4% Tabiy Yo'qotish")),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': " Gazdi 1.4% Yo'qotish",
                'verbose_name_plural': " Gazdi 1.4% Yo'qotish",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Saleprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleprice', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gazdi olingan narxi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': ' Gazdi sotuv narxi',
                'verbose_name_plural': 'Gazdi sotuv narxi',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Credit_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kredit income')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kredit_income', to='reports.filial', verbose_name='Kredit_income')),
            ],
            options={
                'verbose_name': 'Kredit income',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.IntegerField(blank=True, default=0, null=True, verbose_name="Kredit to'lov")),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kredit', to='reports.filial', verbose_name='Kredit')),
            ],
            options={
                'verbose_name': "Kredit to'lov",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Company_XR_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tashkilot income')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies_income', to='reports.filial', verbose_name='Tashkilot_income')),
            ],
            options={
                'verbose_name': 'Tashkilotlar Income X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Company_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tashkilot xisob')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tashkilot', to='reports.filial', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Aksiz_XR_outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aksiz outcome')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aksiz_outcome', to='reports.filial', verbose_name='Aksiz_outcome')),
            ],
            options={
                'verbose_name': 'Aksiz Outcome X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Aksiz_XR_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aksiz income')),
                ('outcome', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aksiz outcome')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aksiz_income', to='reports.filial', verbose_name='Aksiz_income')),
            ],
            options={
                'verbose_name': 'Aksiz Income X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Aksiz_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aksiz xisob')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aksiz', to='reports.filial', verbose_name='Aksiz')),
            ],
            options={
                'verbose_name': 'Aksiz xisob',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Addmaingas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mian_gas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gaz xisoblagich')),
                ('last_gas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sotib olingan gaz(kub)')),
                ('buygasprice', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gaz olinga narx')),
                ('aksiz', models.IntegerField(blank=True, default=0, null=True, verbose_name="Aksiz solig' narx")),
                ('buy_sum', models.IntegerField(blank=True, default=0, null=True, verbose_name='Umumiy(ol sum)')),
                ('aksiz_sum', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aksiz olingan narxi')),
                ('date', models.DateField(verbose_name='Vaqt')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filials', to='reports.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Asosiy gaz xisoblagich',
                'verbose_name_plural': 'Asosiy gaz xisoblagich X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Income_XRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(blank=True, default=0, null=True, verbose_name='Summa')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filial', to='reports.filial', verbose_name='Qaysi fililalga')),
                ('income', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='income', to='reports.incomes', verbose_name='Qayerga')),
            ],
            options={
                'verbose_name': "Xisob raqamga pul o'tkaz",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Main_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.IntegerField(blank=True, default=0, null=True, verbose_name='Umumiy')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filal_main_xr', to='reports.filial', verbose_name='Main_XR')),
            ],
            options={
                'verbose_name': 'Asosiy X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Main_XR_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Main_income')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_income', to='reports.filial', verbose_name='Main_XR_income')),
            ],
            options={
                'verbose_name': 'Asosiy Income X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Main_XR_outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField(blank=True, default=0, null=True, verbose_name='Main_outcome')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_outcome', to='reports.filial', verbose_name='Main_XR_outcome')),
            ],
            options={
                'verbose_name': 'Asosiy Outcome X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Manag_add_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Xisoblagich')),
                ('total_gas_card', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sotilga gas')),
                ('total_sum', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sotilgan gaz puli')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_filial', to='reports.filial', verbose_name='Card_Filiali')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sotilgan gaz puli',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Manag_add_gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalonka_1', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='1 chi kalonka')),
                ('kalonka_2', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='2 chi kalonka')),
                ('kalonka_3', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='3 chi kalonka')),
                ('kalonka_4', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='4 chi kalonka')),
                ('kalonka_5', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='5 chi kalonka')),
                ('kalonka_6', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='6 chi kalonka')),
                ('kalonka_7', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='7 chi kalonka')),
                ('kalonka_8', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='8 chi kalonka')),
                ('total_gas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Umumiy gas')),
                ('remain_gas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sotilgan gaz')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_filial', to='reports.filial', verbose_name='Manager_filiali')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Zapravka sotgan gazi',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Manag_totals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Xisoblagich')),
                ('total_gas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sotilgan gaz')),
                ('lose_gas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="1,4% Yo'qotish")),
                ('gas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Gazning ta'ni")),
                ('sale_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Gazning sotish narxi')),
                ('chec', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Naqt')),
                ('card', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Plastikga')),
                ('sum_half', models.PositiveIntegerField(default=0, verbose_name='Daromat')),
                ('company', models.PositiveIntegerField(default=0, verbose_name='Tashkilotga')),
                ('total_sum', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Umumiy sovda')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='total_filial', to='reports.filial', verbose_name='Total_Filiali')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Zapravka xisoboti',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Xudud_XR_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Xudud income')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='xudud_income', to='reports.filial', verbose_name='Xudud_income')),
            ],
            options={
                'verbose_name': 'Xudud gaz Income X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Xudud_XR_outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField(blank=True, default=0, null=True, verbose_name='Xudud_outcome')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='xudud_outcome', to='reports.filial', verbose_name='Xudud_outcome')),
            ],
            options={
                'verbose_name': 'Xudud gaz Outcome X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Xududgaz_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.IntegerField(blank=True, default=0, null=True, verbose_name='Xududgaz xisob')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='xududgaz', to='reports.filial', verbose_name='Xududgaz')),
            ],
            options={
                'verbose_name': 'Xududgaz xisob',
                'ordering': ['-id'],
            },
        ),
    ]
