# Generated by Django 5.0.4 on 2024-05-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(blank=True, max_length=50, verbose_name='Xarajat')),
                ('profit', models.CharField(blank=True, max_length=50, verbose_name='Daromat')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Asosiy X/R',
                'ordering': ['-id'],
            },
        ),
    ]
