# Generated by Django 5.0.4 on 2024-06-06 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyprice', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gazdi sotilgan narxi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': ' Gazdi olingan narxi',
                'verbose_name_plural': 'Gazdi olingan narxi',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Filial nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Losegas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('losegas', models.FloatField(blank=True, default=1.4, null=True, verbose_name="1.4% Tabiy Yo'qotish")),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': " Gazdi 1.4% Yo'qotish",
                'verbose_name_plural': " Gazdi 1.4% Yo'qotish",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Saleprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleprice', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gazdi olingan narxi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': ' Gazdi sotuv narxi',
                'verbose_name_plural': 'Gazdi sotuv narxi',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Addmaingas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_gas', models.IntegerField(verbose_name='Sotib olingan gaz(kub)')),
                ('mian_gas', models.IntegerField(verbose_name='Gaz(kub)')),
                ('lose', models.FloatField(blank=True, null=True, verbose_name="1.4% Yo'q")),
                ('remain', models.FloatField(blank=True, null=True, verbose_name='Tani')),
                ('buygasprice', models.IntegerField(blank=True, null=True, verbose_name='Olinga narx')),
                ('salegasprice', models.IntegerField(blank=True, null=True, verbose_name='Sotilgan narx')),
                ('sum', models.IntegerField(blank=True, null=True, verbose_name='Umumiy(sum)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filials', to='reports.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Asosiy gaz xisoblagich',
                'verbose_name_plural': 'Asosiy gaz xisoblagich X/R',
            },
        ),
    ]
