# Generated by Django 5.0.4 on 2024-05-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_xr',
            name='expense',
            field=models.FloatField(max_length=50, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='main_xr',
            name='profit',
            field=models.FloatField(max_length=50, null=True, verbose_name='Daromat'),
        ),
    ]
