# Generated by Django 5.0.4 on 2024-06-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaingas',
            name='last_gas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sotib olingan gaz(kub)'),
        ),
    ]
