# Generated by Django 5.0.4 on 2024-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_main_xr_expense_alter_main_xr_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citygas_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Xarajat')),
                ('profit', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Daromat')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Xudud gaz X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='main_xr',
            name='expense',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='main_xr',
            name='profit',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Daromat'),
        ),
    ]
