# Generated by Django 5.0.4 on 2024-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_manag_totals_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manag_totals',
            name='card',
            field=models.PositiveIntegerField(verbose_name='Plastikga'),
        ),
        migrations.AlterField(
            model_name='manag_totals',
            name='company',
            field=models.PositiveIntegerField(verbose_name='Tashkilotga'),
        ),
        migrations.AlterField(
            model_name='manag_totals',
            name='sum_half',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Daromat'),
        ),
    ]
