# Generated by Django 5.0.4 on 2024-06-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_addmaingas_last_gas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addmaingas',
            options={'ordering': ['-id'], 'verbose_name': 'Asosiy gaz xisoblagich', 'verbose_name_plural': 'Asosiy gaz xisoblagich X/R'},
        ),
        migrations.AlterField(
            model_name='addmaingas',
            name='mian_gas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gaz(kub)'),
        ),
    ]
