# Generated by Django 5.0.4 on 2024-05-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_citygas_xr_alter_main_xr_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiz_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Xarajat')),
                ('profit', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Daromat')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Aksiz X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Credir_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Xarajat')),
                ('profit', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Daromat')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Kredit X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Election_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Xarajat')),
                ('profit', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Daromat')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Elektrosvet X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Others_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Xarajat')),
                ('profit', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Daromat')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Boshqa X/R',
                'verbose_name_plural': 'Boshqalar X/R',
                'ordering': ['-id'],
            },
        ),
    ]
