# Generated by Django 5.0.4 on 2024-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_addmaingas_options_alter_addmaingas_mian_gas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmaingas',
            name='sum',
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='bay_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umumiy(ol sum)'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='sale_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umumiy(sot sum)'),
        ),
    ]
