# Generated by Django 5.0.4 on 2024-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_manag_totals_card_alter_manag_totals_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manag_add_card',
            name='lose_gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Gazni ta'ni"),
        ),
        migrations.AddField(
            model_name='manag_add_gas',
            name='lose_gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Gazni ta'ni"),
        ),
    ]
