# Generated by Django 5.0.4 on 2024-06-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_addmaingas_sum_addmaingas_bay_sum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmaingas',
            old_name='bay_sum',
            new_name='buy_sum',
        ),
    ]
