# Generated by Django 5.0.4 on 2024-06-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_manag_add_card_lose_gas_manag_add_gas_lose_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manag_add_gas',
            name='total_gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Gaz xisoblagich'),
        ),
    ]
