# Generated by Django 5.0.4 on 2024-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_aksiz_xr_credir_xr_election_xr_others_xr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmaingas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.IntegerField(max_length=50, verbose_name='Gaz(kub)')),
                ('salegasprice', models.IntegerField(max_length=50, verbose_name='Sotilgan narx')),
            ],
            options={
                'verbose_name': 'Asosiy schyotchik ',
                'verbose_name_plural': 'Asosiy schyotchik X/R',
                'ordering': ['-id'],
            },
        ),
    ]
