# Generated by Django 5.0.4 on 2024-05-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_addmaingas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aksiz_xr',
            name='profit',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='citygas_xr',
            name='profit',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='credir_xr',
            name='expense',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='credir_xr',
            name='profit',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='election_xr',
            name='profit',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='main_xr',
            name='expense',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='others_xr',
            name='expense',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='others_xr',
            name='profit',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Daromat'),
        ),
    ]
