# Generated by Django 5.0.4 on 2024-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_manag_add_gas_total_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='manag_add_card',
            name='gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Gazni ta'ni"),
        ),
        migrations.AddField(
            model_name='manag_add_gas',
            name='gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Gazni ta'ni"),
        ),
        migrations.AlterField(
            model_name='manag_add_gas',
            name='lose_gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="1.4 % yo'qotish"),
        ),
    ]
