# Generated by Django 5.0.4 on 2024-06-07 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_bay_sum_addmaingas_buy_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField(blank=True, default=0, null=True, verbose_name='Xarajat')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Daromat')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filal_main_xr', to='reports.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Xudud gaz X/R',
                'ordering': ['-id'],
            },
        ),
    ]
