# Generated by Django 5.0.4 on 2024-06-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_main_xr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_xr',
            options={'ordering': ['-id'], 'verbose_name': 'Asosiy X/R'},
        ),
        migrations.AddField(
            model_name='main_xr',
            name='main_xr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Umumiy0'),
        ),
    ]
