# Generated by Django 5.0.4 on 2024-05-17 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_aksiz_xr_profit_alter_citygas_xr_profit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addmaingas',
            options={'ordering': ['-id'], 'verbose_name': 'GAZ xisoblagich', 'verbose_name_plural': 'Gaz xisoblagichlar X/R'},
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='buygasprice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Olinga narx'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='cardprofid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Plastik sovda'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Vaqt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='mian_gas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Gaz(kub)'),
        ),
        migrations.AlterField(
            model_name='addmaingas',
            name='gas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Gaz(kub)'),
        ),
        migrations.AlterField(
            model_name='addmaingas',
            name='salegasprice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sotilgan narx'),
        ),
        migrations.AlterField(
            model_name='aksiz_xr',
            name='expense',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='aksiz_xr',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='citygas_xr',
            name='expense',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='citygas_xr',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='credir_xr',
            name='expense',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='credir_xr',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='election_xr',
            name='expense',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='election_xr',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='main_xr',
            name='expense',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='main_xr',
            name='profit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Daromat'),
        ),
        migrations.AlterField(
            model_name='others_xr',
            name='expense',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='others_xr',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Daromat'),
        ),
    ]
