# Generated by Django 5.0.4 on 2024-06-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_manag_add_card_gas_manag_add_gas_gas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manag_add_card',
            name='lose_gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="1.4 % yo'qotish"),
        ),
    ]
