# Generated by Django 5.0.4 on 2024-06-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_main_xr_options_main_xr_main_xr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_xr',
            old_name='main_xr',
            new_name='main',
        ),
    ]
