# Generated by Django 5.0.4 on 2024-06-21 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_manag_totals_card_alter_manag_totals_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aksiz_xr_income',
            name='outcome',
        ),
        migrations.AddField(
            model_name='main_xr_outcome',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 6, 21, 5, 51, 19, 194864, tzinfo=datetime.timezone.utc), verbose_name='Izoh'),
            preserve_default=False,
        ),
    ]
