# Generated by Django 5.0.4 on 2024-06-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_main_xr_income_remove_main_xr_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_xr',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filal_main_xr', to='reports.filial', verbose_name='Main_XR'),
        ),
        migrations.CreateModel(
            name='Main_XR_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Main_income')),
                ('outcome', models.IntegerField(blank=True, default=0, null=True, verbose_name='Main_outcome')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_in_out', to='reports.filial', verbose_name='Main_XR_in_out')),
            ],
            options={
                'verbose_name': 'Asosiy IN OUT X/R',
                'ordering': ['-id'],
            },
        ),
    ]
