# Generated by Django 5.0.4 on 2024-06-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_aksiz_xr_income_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manag_totals',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
    ]
