# Generated by Django 5.0.4 on 2024-06-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_manag_totals_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name="Boshqalar uchun to'lov")),
                ('description', models.TextField(verbose_name='Izoh')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='others', to='reports.filial', verbose_name='Boshqalar')),
            ],
            options={
                'verbose_name': "Boshqalar uchun to'lov",
                'ordering': ['-id'],
            },
        ),
    ]
