# Generated by Django 5.0.4 on 2024-06-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_aksiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xududgaz_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.IntegerField(blank=True, default=0, null=True, verbose_name='Xududgaz xisob')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='xududgaz', to='reports.filial', verbose_name='Xududgaz')),
            ],
            options={
                'verbose_name': 'Xududgaz xisob',
                'ordering': ['-id'],
            },
        ),
    ]
