# Generated by Django 5.0.4 on 2024-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_send_alter_addmaingas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='send_tax',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name="Pul o'tkazish %'"),
        ),
    ]
