# Generated by Django 5.0.4 on 2024-06-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_xududgaz_xr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xudud_XR_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Xudud income')),
                ('outcome', models.IntegerField(blank=True, default=0, null=True, verbose_name='Xudud_outcome')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='xudud_in_out', to='reports.filial', verbose_name='Xudud_in_out')),
            ],
            options={
                'verbose_name': 'Xudud gaz IN OUT X/R',
                'ordering': ['-id'],
            },
        ),
    ]
