# Generated by Django 5.0.4 on 2024-06-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_send_send_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_xr',
            options={'verbose_name': 'Asosiy X/R', 'verbose_name_plural': 'Asosiy X/R'},
        ),
    ]
