# Generated by Django 5.0.4 on 2024-06-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_main_xr_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmaingas',
            name='mian_gas',
        ),
    ]
