# Generated by Django 5.0.4 on 2024-06-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_remove_addmaingas_mian_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manag_add_card',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='manag_add_gas',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
    ]
