# Generated by Django 5.0.4 on 2024-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_manag_add_card_date_alter_manag_add_gas_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manag_add_gas',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sotilgan gaz puli'),
        ),
    ]
