# Generated by Django 5.0.4 on 2024-06-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_manag_add_gas_total_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manag_add_gas',
            options={'ordering': ['-id'], 'verbose_name': 'Zapravka sotgan gazi', 'verbose_name_plural': 'Zapravka sotgan gazi'},
        ),
        migrations.AlterModelOptions(
            name='manag_totals',
            options={'ordering': ['-id'], 'verbose_name': 'Zapravka xisoboti', 'verbose_name_plural': 'Zapravka xisoboti'},
        ),
        migrations.DeleteModel(
            name='Manag_add_card',
        ),
    ]
