# Generated by Django 5.0.4 on 2024-06-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_alter_manag_add_gas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aksiz',
            options={'ordering': ['-id'], 'verbose_name': " Elektor solig'", 'verbose_name_plural': " Elektor solig'"},
        ),
        migrations.AlterModelOptions(
            name='buyprice',
            options={'ordering': ['-id'], 'verbose_name': ' Gazni olingan narxi', 'verbose_name_plural': 'Gazni olingan narxi'},
        ),
        migrations.AlterModelOptions(
            name='losegas',
            options={'ordering': ['-id'], 'verbose_name': " Gazni 1.4% Yo'qotish", 'verbose_name_plural': " Gazni 1.4% Yo'qotish"},
        ),
        migrations.AlterModelOptions(
            name='saleprice',
            options={'ordering': ['-id'], 'verbose_name': ' Gazni sotuv narxi', 'verbose_name_plural': 'Gazni sotuv narxi'},
        ),
        migrations.RemoveField(
            model_name='aksiz',
            name='aksiz',
        ),
        migrations.AddField(
            model_name='aksiz',
            name='elector',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Elektor solig'"),
        ),
        migrations.AlterField(
            model_name='saleprice',
            name='saleprice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Gazni olingan narxi'),
        ),
        migrations.CreateModel(
            name='Elector_XR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Elektro svet xisob')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='elctor', to='reports.filial', verbose_name='Elektrosvet')),
            ],
            options={
                'verbose_name': 'Elektro svet',
                'verbose_name_plural': 'Elektro svet',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Elector_XR_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Elektor income')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='elctor_income', to='reports.filial', verbose_name='Elektor_income')),
            ],
            options={
                'verbose_name': 'Elektor svet income X/R',
                'verbose_name_plural': 'Elektor svet income X/R',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Elector_XR_outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField(blank=True, default=0, null=True, verbose_name='Elektor outcome')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='elctor_outcome', to='reports.filial', verbose_name='Elektor_outcome')),
            ],
            options={
                'verbose_name': 'Elektor svet outcomeX/R',
                'verbose_name_plural': 'Elektor svet outcome X/R',
                'ordering': ['-id'],
            },
        ),
    ]
