# Generated by Django 5.0.4 on 2024-06-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_aksiz_options_alter_buyprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elector', models.IntegerField(blank=True, default=0, null=True, verbose_name="Elektor solig'")),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': " Elektor solig'",
                'verbose_name_plural': " Elektor solig'",
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='aksiz',
            options={'ordering': ['-id'], 'verbose_name': " Aksiz solig'", 'verbose_name_plural': " Aksiz solig'"},
        ),
        migrations.RemoveField(
            model_name='aksiz',
            name='elector',
        ),
        migrations.AddField(
            model_name='aksiz',
            name='aksiz',
            field=models.IntegerField(blank=True, default=680, null=True, verbose_name="Aksiz solig'"),
        ),
    ]
