# Generated by Django 5.0.4 on 2024-07-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_elector_alter_aksiz_options_remove_aksiz_elector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmaingas',
            name='card',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Plastik karta'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='chec',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Naqt'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='company',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tashkilotlar'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='have_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tushgan pul'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='no_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Qolgan pul'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Gazning sotish narxi'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='sum_half',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Daromat'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Umumiy sovda'),
        ),
        migrations.AlterField(
            model_name='addmaingas',
            name='aksiz',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Aksiz solig' narxi"),
        ),
        migrations.AlterField(
            model_name='addmaingas',
            name='buygasprice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Gazning olinga narxi'),
        ),
    ]
