# Generated by Django 5.0.4 on 2024-07-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_addmaingas_elector'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmaingas',
            name='elec_sum',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Elekctorga olingan narxi'),
        ),
    ]
