# Generated by Django 5.0.4 on 2024-07-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_add_bank_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_bank_money',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='add_bank_money', to='reports.filial', verbose_name='Filial'),
        ),
    ]
