# Generated by Django 5.0.4 on 2024-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_addmaingas_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_xr_outcome',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
    ]
