# Generated by Django 5.0.4 on 2024-07-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_addmaingas_humo_addmaingas_naqt_addmaingas_uzcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmaingas',
            name='card_humo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Humo karta'),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='card_uz',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Uzcard karta'),
        ),
        migrations.AddField(
            model_name='manag_totals',
            name='card_humo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Humo karta'),
        ),
        migrations.AddField(
            model_name='manag_totals',
            name='card_uz',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Uzcard karta'),
        ),
        migrations.AlterField(
            model_name='manag_totals',
            name='card',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Plastik karta'),
        ),
    ]
