# Generated by Django 5.0.4 on 2024-07-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_addmaingas_card_humo_addmaingas_card_uz_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_bank_money',
        ),
    ]
