# Generated by Django 5.0.4 on 2024-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_delete_add_bank_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmaingas',
            name='lose_gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Yo'qotilgan gaz"),
        ),
        migrations.AddField(
            model_name='addmaingas',
            name='remain_gas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Qoldiq'),
        ),
    ]
