# Generated by Django 5.0.4 on 2024-07-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_parfum_lose_sanoat_lose_rename_losegas_nasrullo_lose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nasrullo_lose',
            options={'ordering': ['-id'], 'verbose_name': "Nasrullo gazni yo'qotishi", 'verbose_name_plural': " Nasrullo gazni yo'qotishi"},
        ),
        migrations.AlterModelOptions(
            name='parfum_lose',
            options={'ordering': ['-id'], 'verbose_name': " Parfum gazni yo'qotishi", 'verbose_name_plural': " Parfum gazni yo'qotishi"},
        ),
        migrations.AlterModelOptions(
            name='sanoat_lose',
            options={'ordering': ['-id'], 'verbose_name': " Sanoat gazni yo'qotishi", 'verbose_name_plural': " Sanoat gazni yo'qotishi"},
        ),
    ]
