# Generated by Django 5.0.4 on 2024-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_alter_nasrullo_lose_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaingas',
            name='lose_gas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name="Yo'qotilgan gaz"),
        ),
    ]
