# Generated by Django 5.0.4 on 2024-07-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_alter_addmaingas_lose_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_xr',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
    ]
