# Generated by Django 5.0.4 on 2024-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_alter_main_xr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aksiz_xr',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='company_xr',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='elector_xr',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='elector_xr_income',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='others',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='xududgaz_xr',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
    ]
