# Generated by Django 5.0.4 on 2024-07-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_alter_aksiz_xr_date_alter_company_xr_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aksiz_xr',
            options={'verbose_name': 'Aksiz xisob'},
        ),
        migrations.AlterModelOptions(
            name='company_xr',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name': "Kredit to'lov"},
        ),
        migrations.AlterModelOptions(
            name='elector_xr',
            options={'verbose_name': 'Elektro svet', 'verbose_name_plural': 'Elektro svet'},
        ),
        migrations.AlterModelOptions(
            name='others',
            options={'verbose_name': "Boshqalar uchun to'lov"},
        ),
        migrations.AlterModelOptions(
            name='xududgaz_xr',
            options={'verbose_name': 'Xududgaz xisob'},
        ),
        migrations.CreateModel(
            name='Borrow_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Summa')),
                ('date', models.DateField(verbose_name='Vaqt')),
                ('bring_money', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bring_money', to='reports.filial', verbose_name='bring_money')),
                ('get_money', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_money', to='reports.filial', verbose_name='get_money')),
            ],
            options={
                'verbose_name': "O'zaro otkazma",
                'verbose_name_plural': "O'zaro otkazmalar",
            },
        ),
    ]
