# Generated by Django 5.0.4 on 2024-07-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_alter_aksiz_xr_options_alter_company_xr_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_money',
            name='bill',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Summa*'),
        ),
        migrations.AlterField(
            model_name='borrow_money',
            name='bring_money',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bring_money', to='reports.filial', verbose_name='Qayerdan*'),
        ),
        migrations.AlterField(
            model_name='borrow_money',
            name='get_money',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_money', to='reports.filial', verbose_name='Qayerga*'),
        ),
    ]
