# Generated by Django 5.0.4 on 2024-07-21 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_alter_borrow_money_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_xr_income',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 7, 21, 10, 55, 47, 398266, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='Izoh'),
            preserve_default=False,
        ),
    ]
