# Generated by Django 5.0.4 on 2024-07-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_alter_elector_xr_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_xr_income',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_income', to='reports.filial', verbose_name='Qayerga*'),
        ),
        migrations.AlterField(
            model_name='main_xr_income',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Qayerdan*'),
        ),
        migrations.AlterField(
            model_name='main_xr_income',
            name='income',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Summa*'),
        ),
    ]
