# Generated by Django 5.0.4 on 2024-07-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0041_alter_main_xr_income_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_xr',
            options={'ordering': ['-id'], 'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
    ]
