# Generated by Django 5.0.4 on 2024-07-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0042_alter_company_xr_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_xr',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
    ]
