# Generated by Django 5.0.4 on 2024-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_alter_company_xr_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_xr_income',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
    ]
