# Generated by Django 5.0.4 on 2024-07-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0044_alter_company_xr_income_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qarzlar')),
                ('date', models.DateField(verbose_name='Vaqt')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qarzlar', to='reports.filial', verbose_name='Qarzlar')),
            ],
            options={
                'verbose_name': 'Qarzlar',
                'ordering': ['-id'],
            },
        ),
    ]
