# Generated by Django 5.0.4 on 2024-07-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0045_debts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debts',
            options={'ordering': ['-id'], 'verbose_name': 'Qarzlar bergan'},
        ),
        migrations.AlterField(
            model_name='debts',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qarzlar_bergan', to='reports.filial', verbose_name='Qarzlar berilgan'),
        ),
    ]
