# Generated by Django 5.0.4 on 2024-07-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0046_alter_debts_options_alter_debts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_income',
            name='dollar',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dollar'),
        ),
        migrations.AlterField(
            model_name='credit_income',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kredit_income', to='reports.filial', verbose_name='Qaysi filialga'),
        ),
        migrations.AlterField(
            model_name='credit_income',
            name='income',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="So'm"),
        ),
        migrations.AlterField(
            model_name='income_xrs',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial', to='reports.filial', verbose_name='Qaysi fililalga'),
        ),
    ]
