# Generated by Django 5.0.4 on 2024-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0047_credit_income_dollar_alter_credit_income_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_income',
            name='date',
            field=models.DateField(verbose_name='Vaqt'),
        ),
    ]
