# Generated by Django 5.0.4 on 2024-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0049_alter_income_xrs_category_alter_income_xrs_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_xr_outcome',
            name='where',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qayerga'),
        ),
    ]
