# Generated by Django 5.0.4 on 2024-08-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_main_xr_outcome_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_income',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kredit_income', to='reports.filial', verbose_name='Qaysi filial'),
        ),
    ]
