# Generated by Django 5.0.4 on 2024-08-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0051_alter_credit_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_xr_outcome',
            name='out_prot',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Main_outcome'),
        ),
    ]
